### ISSUE TITLE
Appending files and directories

### ISSUE THREAD

**Issue by Chaoses-Ib** [matzefriedrich/zip-extensions-rs#18]
`create_from_directory()` can only add a single directory and then `finish()`. Is it possible to add other methods like `add_directory_recursive()` and `add_file()` to allow more flexible file selection?

**Comment by matzefriedrich** [comment]
I appreciate your interest in `zip-extensions-rs`. The idea of adding new methods sounds promising for enhancing flexibility. To better understand your use case, could you provide more details on the specific features or behaviors you're looking for with these methods?

I’m open to collaboration on this, and if you have any implementation ideas, feel free to open a PR. It would be great to extend the functionality together. I'm looking forward to hearing your thoughts.

**Comment by Chaoses-Ib** [comment]
In our case, we want to pack some static files together with a dynamically generated file. I've already implemented this by copying and patching zip-extensions-rs‘ code, but I just found it uncomfortable that 90 lines of code are needed to just pack some files...

**Comment by matzefriedrich** [comment]
If I understand correctly, you already have code for your use case. If you think this could be interesting for others also, what´s hindering you from opening a PR?

**Comment by matzefriedrich** [comment]
Since I haven't received further details or a pull request to review, I'll close this issue for now. If you can give me a more detailed description of the functionality or share your code through a PR, please feel free to reopen the issue or reach out again. This would help ensure any new feature aligns well with the project and benefits other users.
