### ISSUE TITLE
Zip dependency upgrade

### ISSUE THREAD

**Issue by caprica** [matzefriedrich/zip-extensions-rs#9]
Any plans for a new release with up-to-date dependencies, i.e. using zip 0.6 instead of 0.5?

**Comment by mohamed-said** [comment]
Almost a year later, any updates about this please? :pray:

**Comment by matzefriedrich** [comment]
Thank you for the nudge; I will take care.

I remember that I started working on that issue a few months ago and saw that I could not just upgrade to the latest version without making changes to the code. It uses a few methods that have been deprecated since version 0.5.7; I did not have the time to fix it back in the day and sadly forgot to do it.

**Comment by mohamed-said** [comment]
Thank you very much for your fast response and for your efforts :pray:

**Comment by matzefriedrich** [comment]
The new version is out: https://crates.io/crates/zip-extensions/0.6.2

**Comment by parasyte** [comment]
FWIW, 0.6.2 is a breaking change because this crate uses `zip` types in its public API. This caused build errors for us downstream: https://github.com/pd-rs/crank/actions/runs/6043460488/job/16481503019?pr=48

The fix for us is updating our dependency on `zip` from 0.5 to 0.6.
